-- UCAR 6.0 seed vocabulary and sources.
-- Terms are lowercase lemmas. Embeddings are backfilled by the extract
-- function's ?action=embed_vocab pass after deploy (gte-small, 384-dim).

insert into vocab_terms (kind, term) values
-- verbs
('verb','surveil'),('verb','monitor'),('verb','track'),('verb','identify'),
('verb','recognize'),('verb','screen'),('verb','score'),('verb','rank'),
('verb','flag'),('verb','detect'),('verb','predict'),('verb','profile'),
('verb','classify'),('verb','moderate'),('verb','censor'),('verb','block'),
('verb','deny'),('verb','approve'),('verb','decide'),('verb','diagnose'),
('verb','treat'),('verb','generate'),('verb','impersonate'),('verb','deceive'),
('verb','manipulate'),('verb','persuade'),('verb','recommend'),('verb','target'),
('verb','price'),('verb','hire'),('verb','fire'),('verb','evaluate'),
('verb','grade'),('verb','teach'),('verb','tutor'),('verb','translate'),
('verb','transcribe'),('verb','summarize'),('verb','write'),('verb','design'),
('verb','optimize'),('verb','automate'),('verb','replace'),('verb','assist'),
('verb','navigate'),('verb','drive'),('verb','fly'),('verb','patrol'),
('verb','arrest'),('verb','sentence'),('verb','audit'),('verb','exploit'),
('verb','attack'),('verb','defend'),('verb','scan'),('verb','search'),
('verb','collect'),('verb','infer'),('verb','simulate'),('verb','forecast'),
-- object classes
('object_class','students'),('object_class','workers'),('object_class','employees'),
('object_class','patients'),('object_class','citizens'),('object_class','residents'),
('object_class','consumers'),('object_class','users'),('object_class','children'),
('object_class','job applicants'),('object_class','tenants'),('object_class','borrowers'),
('object_class','drivers'),('object_class','passengers'),('object_class','travelers'),
('object_class','immigrants'),('object_class','prisoners'),('object_class','suspects'),
('object_class','protesters'),('object_class','voters'),('object_class','veterans'),
('object_class','soldiers'),('object_class','shoppers'),('object_class','gamers'),
('object_class','artists'),('object_class','writers'),('object_class','developers'),
('object_class','doctors'),('object_class','teachers'),('object_class','lawyers'),
('object_class','content'),('object_class','images'),('object_class','videos'),
('object_class','documents'),('object_class','communications'),('object_class','transactions'),
('object_class','vehicles'),('object_class','buildings'),('object_class','infrastructure'),
('object_class','crops'),('object_class','wildlife'),('object_class','weapons'),
-- instruments
('instrument','facial recognition'),('instrument','emotion recognition'),
('instrument','image recognition'),('instrument','voice recognition'),
('instrument','gait recognition'),('instrument','license plate readers'),
('instrument','surveillance cameras'),('instrument','drones'),
('instrument','large language models'),('instrument','chatbots'),
('instrument','generative ai'),('instrument','deepfakes'),
('instrument','predictive policing systems'),('instrument','risk assessment algorithms'),
('instrument','recommendation algorithms'),('instrument','content moderation algorithms'),
('instrument','hiring algorithms'),('instrument','credit scoring models'),
('instrument','pricing algorithms'),('instrument','fraud detection systems'),
('instrument','biometric systems'),('instrument','location tracking'),
('instrument','keystroke monitoring'),('instrument','productivity monitoring software'),
('instrument','autonomous vehicles'),('instrument','autonomous weapons'),
('instrument','robots'),('instrument','computer vision'),
('instrument','speech synthesis'),('instrument','voice cloning'),
('instrument','sentiment analysis'),('instrument','natural language processing'),
('instrument','machine learning models'),('instrument','neural networks'),
('instrument','ai agents'),('instrument','ai companions'),
('instrument','ai tutors'),('instrument','ai diagnostic tools'),
('instrument','medical imaging ai'),('instrument','protein folding models'),
('instrument','weather models'),('instrument','trading algorithms'),
('instrument','ad targeting systems'),('instrument','search algorithms'),
('instrument','spam filters'),('instrument','malware detection'),
('instrument','vulnerability scanners'),('instrument','prompt injection')
on conflict (kind, term) do nothing;

insert into sources (name, url, kind) values
('Ars Technica AI',      'https://feeds.arstechnica.com/arstechnica/ai',                     'rss'),
('Ars Technica Tech',    'https://feeds.arstechnica.com/arstechnica/technology-lab',         'rss'),
('EFF Deeplinks',        'https://www.eff.org/rss/updates.xml',                              'rss'),
('The Verge AI',         'https://www.theverge.com/rss/ai-artificial-intelligence/index.xml','rss'),
('Wired AI',             'https://www.wired.com/feed/tag/ai/latest/rss',                     'rss'),
('MIT Tech Review',      'https://www.technologyreview.com/feed/',                           'rss'),
('404 Media',            'https://www.404media.co/rss/',                                     'rss'),
('The Markup',           'https://themarkup.org/feeds/rss.xml',                              'rss'),
('AlgorithmWatch',       'https://algorithmwatch.org/en/feed/',                              'rss'),
('Rest of World',        'https://restofworld.org/feed/latest/',                             'rss'),
('TechCrunch AI',        'https://techcrunch.com/category/artificial-intelligence/feed/',    'rss'),
('VentureBeat AI',       'https://venturebeat.com/category/ai/feed/',                        'rss'),
('The Register AI',      'https://www.theregister.com/software/ai_ml/headlines.atom',        'rss'),
('Krebs on Security',    'https://krebsonsecurity.com/feed/',                                'rss'),
('Schneier on Security', 'https://www.schneier.com/feed/atom/',                              'rss')
on conflict (url) do nothing;
